[env:esp32s3_supermini]
platform = espressif32
board = esp32s3_supermini
framework = arduino
monitor_speed = 115200
build_flags =
    -mfix-esp32-psram-cache-issue
lib_deps =
    olikraus/U8g2 @ ^2.34.22
